esphome:
  name: dr4go-test
  friendly_name: dr4go test

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable Home Assistant API
api:
  encryption:
    key: "InO946QM3MM0MJ3uvi98tWFDfHUhdUyPqZ/aY8wL7u8="

ota:
  - platform: esphome
    password: "4c891f7b63e9d9a02f052eb9092e75d5"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "dr4go test Fallback Hotspot"
    password: "ad9d9329sdas"

captive_portal:

external_components:
  - source: components
    components: [vl53l0x_lib]

logger:
  level: DEBUG

i2c:
  sda: 21
  scl: 22
  scan: false
  id: bus_a
  frequency: 100000

sensor:
  - platform: vl53l0x_lib
    name: "Waschbecken Abstand"
    
    # Sensing mode: default | long_range | high_speed | high_accuracy
    sense_mode: default
    
    # Quality filtering
    enable_sigma_check: true
    enable_signal_check: true
    
    # Optional: explicit timing budget (overrides sense_mode timing)
    # timing_budget: 33ms
    
    # Optional: calibration settings
    # offset_calibration: 0       # micrometers (-512000 to +511000)
    # crosstalk_compensation: 0.0 # MCPS (0.0 to 10.0)
    
    # Standard options
    signal_rate_limit: 0.25
    timeout: 10ms
    update_interval: 1s
