esphome:
  name: bad

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: github://zaolin/vl53l0x@main
    components: [vl53l0x_lib]

logger:
  level: DEBUG

api:
  encryption:
    key: InO946QM3MM0MJ3uvi98tWFDfHUhdUyPqZ/aY8wL7u8=

wifi:
  ssid: "ZDS"
  password: "blafoo234211sicher"
  fast_connect: on

i2c:
  sda: 21
  scl: 22
  scan: false
  id: bus_a
  frequency: 100000

sensor:
  - platform: vl53l0x_lib
    name: "Waschbecken Abstand"
    update_interval: 1s
